name: downsampling
language: Python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: table-data
    required: false
  - name: output
    inputType: OutputTopic
    defaultValue: table-data-10s
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
