name: file-sink
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: raw-data
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
